apiVersion: v1
kind: ConfigMap # where we hide varialbes and secrets 
metadata:
  name: eazybank-configmap
data:
  SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/  # same zipkin-service from zipkin file and same port
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
