apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: eazybytes/configserver:latest
        ports:
        - containerPort: 8071  # same of target port
        env:                          #this to tell that it has to connect with zipkin and under which profile it has to run 
        - name: SPRING_ZIPKIN_BASEURL # this config u have to handle using config inside k8s 
          valueFrom:                  #config map in k8s help to have the vaiables and secrets 
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: SPRING_PROFILES_ACTIVE
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
